markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: 

repository: 
help_url: 

collections:
  docs:
    output: true

name:  Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: http://sonjasper.com/project/

gems:
  - jekyll-feed
